# Generated by Django 5.2 on 2025-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на телеграмм'),
        ),
    ]
