# Generated by Django 5.2 on 2025-05-17 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=127, null=True, unique=True, verbose_name='slug')),
                ('address', models.CharField(max_length=127, unique=True, verbose_name='Адрес')),
                ('link_to_map', models.URLField(max_length=127, unique=True, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Адррес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=127, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=127, null=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=127, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/%Y/%m/%d/', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.address', verbose_name='Адрес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.categories', verbose_name='Категория')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.condition', verbose_name='Состояние')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'goods',
                'ordering': ['-time_create'],
            },
        ),
    ]
