# Generated by Django 5.2 on 2025-05-22 12:53

import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=goods.models.upload_to, verbose_name='Изображение'),
        ),
    ]
